data(iris)
install.packages("rpart")
library(rpart)
model<-rpart(Species~Sepal.Length+Sepal.Width+Petal.Length+Petal.Width,iris)
testIris = read.csv("E:/testIris.csv")
pred <- predict(model, testIris, type="class") 
install.packages("caret")
library(caret)
c<-confusionMatrix(pred, testIris$Species)
print(c)
install.packages("rpart.plot")
library(rpart.plot)
prp(model)

